name: violence-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - scipy=1.11.4
  - ffmpeg=6.1.1
  - libsndfile=1.2.2
  - pip
  - pip:
    - setuptools<70
    - tensorflow-macos==2.15.0
    - tensorflow-hub==0.16.1
    - librosa==0.10.1
    - soundfile==0.12.1
    - openai==1.13.3
    - groq==0.6.0
    - ultralytics==8.1.0
    - opencv-python==4.9.0.80
    - torch==2.2.0
    - torchvision==0.17.0
    - torchaudio==2.2.0
    - file:///Users/kausar/Documents/moment-to-action/third_party/mobileclip
