"""LLM-layer messages for language-model reasoning outputs."""

from __future__ import annotations

from ._base import BaseMessage


class ReasoningMessage(BaseMessage):
    """Output from a large-language-model reasoning step."""

    response: str
    """The raw text generated by the LLM."""

    prompt: str
    """The exact prompt that was submitted to the model."""

    latency_ms: float  # type: ignore[assignment]  # override optional base field as required
    """Wall-clock inference time in milliseconds."""
