"""LLM-layer messages for language-model reasoning outputs."""

from __future__ import annotations

from ._base import BaseMessage


class ReasoningMessage(BaseMessage):
    """Output from a large-language-model reasoning step.

    Carries the model's textual response together with the prompt that
    produced it and a latency figure for performance monitoring.

    Attributes:
        response: The raw text generated by the LLM.
        prompt: The exact prompt that was submitted to the model.
        latency_ms: Wall-clock inference time in milliseconds.
    """

    response: str
    prompt: str
    latency_ms: float
