"""Scoring functions for benchmark evaluation: keyword recall, yes/no detection, AP50."""

from __future__ import annotations

import re

import numpy as np

_IOU_THRESHOLD_AP50 = 0.5


def recall(response: str, keywords: list[str]) -> float:
    """Compute keyword recall: fraction of expected keywords found in the response.

    Args:
        response: Text generated by the model.
        keywords: Words expected from a correct answer (case-insensitive match).

    Returns:
        Fraction in [0, 1] of keywords found. ``1.0`` when *keywords* is empty.
    """
    if not keywords:
        return 1.0
    resp_lower = response.lower()
    found = sum(1 for kw in keywords if kw.lower() in resp_lower)
    return found / len(keywords)


def detect_yn(text: str) -> str | None:
    """Return "yes" or "no" if *text* contains a yes/no answer, else ``None``.

    Matches two formats:
    - Leading word: ``"YES, because..."`` / ``"No."``
    - Labelled: ``"Answer: YES"`` / ``"Answer: No"``

    Args:
        text: Accumulated model response so far.

    Returns:
        "yes", "no", or ``None`` if not yet decidable.
    """
    cleaned = text.strip().lower()
    words = cleaned.split()
    if words and words[0].rstrip(".,!?;:") in {"yes", "no"}:
        return words[0].rstrip(".,!?;:")
    m = re.search(r"\banswer\s*:\s*(yes|no)\b", cleaned)
    if m:
        return m.group(1)
    return None


def _iou_np(box_a: np.ndarray, boxes_b: np.ndarray) -> np.ndarray:
    """Compute IoU between one box and an array of boxes.

    Args:
        box_a: Shape ``(4,)`` array ``[x1, y1, x2, y2]``.
        boxes_b: Shape ``(N, 4)`` array.

    Returns:
        IoU values, shape ``(N,)``.
    """
    x1 = np.maximum(box_a[0], boxes_b[:, 0])
    y1 = np.maximum(box_a[1], boxes_b[:, 1])
    x2 = np.minimum(box_a[2], boxes_b[:, 2])
    y2 = np.minimum(box_a[3], boxes_b[:, 3])
    inter = np.maximum(0.0, x2 - x1) * np.maximum(0.0, y2 - y1)
    area_a = (box_a[2] - box_a[0]) * (box_a[3] - box_a[1])
    area_b = (boxes_b[:, 2] - boxes_b[:, 0]) * (boxes_b[:, 3] - boxes_b[:, 1])
    union = area_a + area_b - inter
    return inter / (union + 1e-6)


def ap50(pred_boxes: np.ndarray, pred_scores: np.ndarray, gt_boxes: np.ndarray) -> float:
    """Compute AP50 for a single image (IoU threshold 0.5).

    Args:
        pred_boxes: ``(N, 4)`` predicted boxes ``[x1, y1, x2, y2]``.
        pred_scores: ``(N,)`` confidence scores.
        gt_boxes: ``(M, 4)`` ground-truth boxes ``[x1, y1, x2, y2]``.

    Returns:
        Average precision at IoU>=0.5. ``1.0`` when both *gt_boxes* and
        *pred_boxes* are empty; ``0.0`` when *gt_boxes* is non-empty but
        *pred_boxes* is empty (or vice versa).
    """
    if len(gt_boxes) == 0:
        return 1.0 if len(pred_boxes) == 0 else 0.0
    if len(pred_boxes) == 0:
        return 0.0

    order = np.argsort(pred_scores)[::-1]
    pred_boxes = pred_boxes[order]

    matched = np.zeros(len(gt_boxes), dtype=bool)
    tp = np.zeros(len(pred_boxes))
    fp = np.zeros(len(pred_boxes))

    for i, pb in enumerate(pred_boxes):
        ious = _iou_np(pb, gt_boxes)
        best = int(np.argmax(ious))
        if ious[best] >= _IOU_THRESHOLD_AP50 and not matched[best]:
            tp[i] = 1
            matched[best] = True
        else:
            fp[i] = 1

    cum_tp = np.cumsum(tp)
    cum_fp = np.cumsum(fp)
    n_gt = float(len(gt_boxes))
    precision = cum_tp / (cum_tp + cum_fp + 1e-6)
    recall_curve = cum_tp / n_gt

    ap = 0.0
    prev_r = 0.0
    for p, r in zip(precision, recall_curve, strict=True):
        ap += p * (r - prev_r)
        prev_r = r
    return float(ap)
